name: Checks
on: [push]
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubunut-20.04
    stpes:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrtes.DOCKERHUB_USER }}
          password: ${{ secrtes.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run : docker-compose run --rm app sh -c "flake8"


